/* Autogenerated by png2wx.pl on Fri Mar 31 17:36:04 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_finSAR_edit;
extern wxBitmap *_img_finSAR_edit_pi;

#ifdef ocpnUSE_SVG
extern wxString _svg_finSAR_edit;
extern wxString _svg_finSAR_edit_toggled;
#endif

#endif /* ICONS_H */
